const quizBank = {
  'react.js advanced': [
    { questionText: 'What is the purpose of the useMemo hook?', options: ['To memoize a function definition', 'To cache the result of a calculation between renders', 'To trigger a re-render', 'To manage global state'], correctAnswer: 'To cache the result of a calculation between renders' },
    { questionText: 'How does React 18 concurrent mode improve rendering?', options: ['By making rendering interruptible', 'By removing the Virtual DOM', 'By running on multiple CPU threads', 'By rendering directly to the DOM'], correctAnswer: 'By making rendering interruptible' },
    { questionText: 'What is a Higher-Order Component (HOC)?', options: ['A component rendered at the top of the tree', 'A function that takes a component and returns a new component', 'A state management library', 'A component with more than 10 props'], correctAnswer: 'A function that takes a component and returns a new component' },
    { questionText: 'Which lifecycle method is replaced by the useEffect hook cleanup function?', options: ['componentDidMount', 'componentDidUpdate', 'componentWillUnmount', 'shouldComponentUpdate'], correctAnswer: 'componentWillUnmount' },
    { questionText: 'What is the primary use case for React.forwardRef?', options: ['Passing a ref through a component to one of its children', 'Forwarding events to parent components', 'Caching component state', 'Routing to another page'], correctAnswer: 'Passing a ref through a component to one of its children' },
    { questionText: 'How does Context API differ from Redux?', options: ['Context is only for class components', 'Context is built-in and lacks middleware support', 'Redux is faster for all use cases', 'Context cannot hold complex objects'], correctAnswer: 'Context is built-in and lacks middleware support' },
    { questionText: 'What causes a React component to re-render?', options: ['Only when props change', 'Only when state changes', 'When state or props change, or the parent re-renders', 'When the browser window is resized'], correctAnswer: 'When state or props change, or the parent re-renders' },
    { questionText: 'What is the Virtual DOM?', options: ['A direct copy of the actual DOM', 'A lightweight JavaScript representation of the DOM', 'A browser extension for debugging', 'A CSS framework'], correctAnswer: 'A lightweight JavaScript representation of the DOM' },
    { questionText: 'How do you pass data from a child back to a parent component?', options: ['Using Context', 'Using a callback function passed as a prop', 'Using Redux', 'Using window.localStorage'], correctAnswer: 'Using a callback function passed as a prop' },
    { questionText: 'What does useCallback do?', options: ['Memoizes a function definition', 'Memoizes a computed value', 'Runs a side effect', 'Fetches data from an API'], correctAnswer: 'Memoizes a function definition' },
    { questionText: 'What is a custom hook in React?', options: ['A hook provided by a third-party library', 'A JavaScript function whose name starts with "use" that calls other hooks', 'A class component method', 'A hook that manipulates the DOM directly'], correctAnswer: 'A JavaScript function whose name starts with "use" that calls other hooks' },
    { questionText: 'Why shouldn\'t you mutate state directly in React?', options: ['It causes a syntax error', 'It prevents React from knowing the state changed and triggering a re-render', 'It deletes the component', 'It causes infinite loops'], correctAnswer: 'It prevents React from knowing the state changed and triggering a re-render' },
    { questionText: 'What is the purpose of React.Fragment?', options: ['To group multiple elements without adding an extra node to the DOM', 'To create a shadow DOM', 'To split code into chunks', 'To render HTML strings safely'], correctAnswer: 'To group multiple elements without adding an extra node to the DOM' },
    { questionText: 'What is Prop Drilling?', options: ['Passing props down multiple levels to reach a deeply nested component', 'Extracting props from a component', 'Using props to style components', 'Validating prop types'], correctAnswer: 'Passing props down multiple levels to reach a deeply nested component' },
    { questionText: 'Which hook would you use to reference a DOM element directly?', options: ['useState', 'useRef', 'useEffect', 'useContext'], correctAnswer: 'useRef' },
    { questionText: 'What is hydration in Server-Side Rendering (SSR) with React?', options: ['Fetching data from the database', 'Attaching event listeners to the server-rendered HTML', 'Compressing the JavaScript bundle', 'Converting JSON to React elements'], correctAnswer: 'Attaching event listeners to the server-rendered HTML' },
    { questionText: 'What is a Controlled Component?', options: ['A component that controls its own state internally', 'A component whose form data is handled by React state', 'A component wrapped in a Redux Provider', 'A component that prevents default browser behavior'], correctAnswer: 'A component whose form data is handled by React state' },
    { questionText: 'Which method is best for preventing unnecessary re-renders in a functional component?', options: ['React.memo', 'shouldComponentUpdate', 'useCallback', 'useRef'], correctAnswer: 'React.memo' },
    { questionText: 'What is Suspense in React?', options: ['A way to delay rendering a component until some condition is met, like data loading', 'A lifecycle method for unmounting', 'An error boundary component', 'A state management tool'], correctAnswer: 'A way to delay rendering a component until some condition is met, like data loading' },
    { questionText: 'How can you capture errors in a React component tree?', options: ['Using try-catch in render', 'Using Error Boundaries (componentDidCatch)', 'Using window.onerror', 'Using useEffect'], correctAnswer: 'Using Error Boundaries (componentDidCatch)' }
  ],
  'next.js ssr structures': [
    { questionText: 'What is the main difference between getStaticProps and getServerSideProps?', options: ['getStaticProps runs at build time, getServerSideProps runs on every request', 'They are exactly the same', 'getServerSideProps runs on the client', 'getStaticProps is for API routes'], correctAnswer: 'getStaticProps runs at build time, getServerSideProps runs on every request' },
    { questionText: 'In the Next.js App Router, what is the default rendering strategy for components?', options: ['Client Components', 'Server Components', 'Static Site Generation', 'Single Page Application'], correctAnswer: 'Server Components' },
    { questionText: 'How do you define a Client Component in Next.js App Router?', options: ['By placing it in a "client" folder', 'By adding "use client" at the top of the file', 'By importing React', 'By using the useEffect hook'], correctAnswer: 'By adding "use client" at the top of the file' },
    { questionText: 'What is the purpose of the layout.tsx file?', options: ['To style the application', 'To share UI across multiple pages, preserving state on navigation', 'To define the database schema', 'To handle API requests'], correctAnswer: 'To share UI across multiple pages, preserving state on navigation' },
    { questionText: 'Which file is used to handle 404 Not Found errors in the App Router?', options: ['404.js', 'not-found.tsx', 'error.tsx', 'page.tsx'], correctAnswer: 'not-found.tsx' },
    { questionText: 'What does Incremental Static Regeneration (ISR) do?', options: ['Rebuilds the entire site on a schedule', 'Allows updating static pages after build time without rebuilding the whole site', 'Server-renders all pages dynamically', 'Caches API responses in the browser'], correctAnswer: 'Allows updating static pages after build time without rebuilding the whole site' },
    { questionText: 'How are dynamic routes defined in the App Router?', options: ['Using square brackets (e.g., [id])', 'Using a colon (e.g., :id)', 'Using an underscore (e.g., _id)', 'Using query strings only'], correctAnswer: 'Using square brackets (e.g., [id])' },
    { questionText: 'What is the role of the loading.tsx file?', options: ['To define a loading spinner for Suspense boundaries while a route loads', 'To pre-fetch data', 'To optimize images', 'To handle form submissions'], correctAnswer: 'To define a loading spinner for Suspense boundaries while a route loads' },
    { questionText: 'How can you fetch data on the server in a Server Component?', options: ['Using useEffect', 'Using an async function and await fetch()', 'Using SWR only', 'Using Redux Thunk'], correctAnswer: 'Using an async function and await fetch()' },
    { questionText: 'What is a Server Action in Next.js?', options: ['An API route in the pages folder', 'An asynchronous function executed on the server that can be called directly from components', 'A Redux middleware', 'A webhook handler'], correctAnswer: 'An asynchronous function executed on the server that can be called directly from components' },
    { questionText: 'How does the Next.js Image component optimize images?', options: ['By converting them all to GIF', 'By resizing, optimizing formats (like WebP), and lazy loading', 'By stretching them to fill the screen', 'By storing them in local storage'], correctAnswer: 'By resizing, optimizing formats (like WebP), and lazy loading' },
    { questionText: 'What is the purpose of middleware.ts in Next.js?', options: ['To style components globally', 'To run code before a request is completed, like authentication or redirects', 'To handle database connections', 'To manage React state'], correctAnswer: 'To run code before a request is completed, like authentication or redirects' },
    { questionText: 'Which function is used to programmatically navigate between routes in Client Components?', options: ['useRouter() from next/navigation', 'window.location', 'useNavigate from react-router', 'redirect()'], correctAnswer: 'useRouter() from next/navigation' },
    { questionText: 'Can Server Components pass functions as props to Client Components?', options: ['Yes, always', 'No, functions are not serializable', 'Only if the function is a Server Action', 'Only if the function returns a string'], correctAnswer: 'No, functions are not serializable' },
    { questionText: 'What does the generateStaticParams function do?', options: ['Generates CSS variables', 'Pre-renders dynamic routes at build time in the App Router', 'Creates API keys', 'Handles form validation'], correctAnswer: 'Pre-renders dynamic routes at build time in the App Router' },
    { questionText: 'How do you implement SEO metadata in the App Router?', options: ['Using the <Head> component', 'Exporting a metadata object or generateMetadata function from a page/layout', 'Using document.title', 'In the next.config.js'], correctAnswer: 'Exporting a metadata object or generateMetadata function from a page/layout' },
    { questionText: 'What is Route Handlers (route.ts) used for?', options: ['Rendering React components', 'Creating custom API endpoints for a given route', 'Routing client-side transitions', 'Handling 404 pages'], correctAnswer: 'Creating custom API endpoints for a given route' },
    { questionText: 'Which environment variable prefix exposes variables to the browser in Next.js?', options: ['REACT_APP_', 'PUBLIC_', 'NEXT_PUBLIC_', 'BROWSER_'], correctAnswer: 'NEXT_PUBLIC_' },
    { questionText: 'What happens when you use the "revalidate" option in a fetch request?', options: ['It triggers a full page reload', 'It sets the cache lifetime for Incremental Static Regeneration (ISR)', 'It validates a JWT token', 'It clears the browser cache'], correctAnswer: 'It sets the cache lifetime for Incremental Static Regeneration (ISR)' },
    { questionText: 'What is Parallel Routing in Next.js?', options: ['Running multiple Next.js servers', 'Simultaneously or conditionally rendering multiple pages in the same layout using slots', 'Fetching data from multiple APIs at once', 'Deploying to multiple regions'], correctAnswer: 'Simultaneously or conditionally rendering multiple pages in the same layout using slots' }
  ],
  'node.js express rest api': [
    { questionText: 'What is Express.js?', options: ['A database', 'A minimalist web framework for Node.js', 'An ORM', 'A testing library'], correctAnswer: 'A minimalist web framework for Node.js' },
    { questionText: 'Which method is used to parse incoming JSON payloads in Express?', options: ['express.json()', 'express.parse()', 'body-parser.url()', 'JSON.parse()'], correctAnswer: 'express.json()' },
    { questionText: 'How do you define a route parameter in Express?', options: ['app.get("/users?id")', 'app.get("/users/:id")', 'app.get("/users/[id]")', 'app.get("/users/{id}")'], correctAnswer: 'app.get("/users/:id")' },
    { questionText: 'What is middleware in Express?', options: ['A database connection string', 'Functions that have access to the request, response, and the next middleware function', 'A frontend templating engine', 'A built-in authentication system'], correctAnswer: 'Functions that have access to the request, response, and the next middleware function' },
    { questionText: 'Which object represents the HTTP response in an Express callback?', options: ['req', 'res', 'next', 'app'], correctAnswer: 'res' },
    { questionText: 'How do you handle errors globally in an Express application?', options: ['Using try-catch in every route', 'Defining a middleware with 4 arguments (err, req, res, next)', 'Using the process.on("error") listener', 'By sending a 500 status manually'], correctAnswer: 'Defining a middleware with 4 arguments (err, req, res, next)' },
    { questionText: 'What does CORS stand for?', options: ['Cross-Origin Resource Sharing', 'Cross-Origin Routing System', 'Central Object Resource Storage', 'Cascading Object Rendering System'], correctAnswer: 'Cross-Origin Resource Sharing' },
    { questionText: 'Which HTTP method is conventionally used to update an entire resource?', options: ['GET', 'POST', 'PUT', 'PATCH'], correctAnswer: 'PUT' },
    { questionText: 'Which HTTP method is conventionally used to partially update a resource?', options: ['PUT', 'PATCH', 'POST', 'UPDATE'], correctAnswer: 'PATCH' },
    { questionText: 'How do you send a JSON response in Express?', options: ['res.sendJSON()', 'res.json()', 'res.end()', 'res.write()'], correctAnswer: 'res.json()' },
    { questionText: 'What is the purpose of the Next function in Express middleware?', options: ['To skip to the next route', 'To pass control to the next middleware function', 'To restart the server', 'To send the response to the client'], correctAnswer: 'To pass control to the next middleware function' },
    { questionText: 'How do you retrieve query parameters from a URL like /users?age=25?', options: ['req.params.age', 'req.query.age', 'req.body.age', 'req.url.age'], correctAnswer: 'req.query.age' },
    { questionText: 'What status code indicates a successful POST request that created a resource?', options: ['200', '201', '204', '400'], correctAnswer: '201' },
    { questionText: 'Which library is commonly used for validating request data in Express?', options: ['Mongoose', 'Joi / express-validator', 'Lodash', 'Bcrypt'], correctAnswer: 'Joi / express-validator' },
    { questionText: 'How can you protect routes using JWT in Express?', options: ['By storing the token in local storage', 'By verifying the token in a middleware before allowing access to the route', 'By encrypting the database', 'By hiding the URL'], correctAnswer: 'By verifying the token in a middleware before allowing access to the route' },
    { questionText: 'What does req.body contain?', options: ['The headers of the request', 'The route parameters', 'The parsed data submitted in the request body', 'The HTML content of the page'], correctAnswer: 'The parsed data submitted in the request body' },
    { questionText: 'Why is it important to use Helmet.js in an Express app?', options: ['To manage database connections', 'To set various HTTP headers for security', 'To parse cookies', 'To compress responses'], correctAnswer: 'To set various HTTP headers for security' },
    { questionText: 'What is a RESTful API?', options: ['An API that never sleeps', 'An architectural style based on representing state transfer over HTTP', 'A GraphQL implementation', 'A database schema'], correctAnswer: 'An architectural style based on representing state transfer over HTTP' },
    { questionText: 'How do you start an Express server listening on a port?', options: ['app.start(port)', 'app.run(port)', 'app.listen(port)', 'server.init(port)'], correctAnswer: 'app.listen(port)' },
    { questionText: 'What is the Event Loop in Node.js?', options: ['A for-loop that processes arrays', 'The mechanism that handles asynchronous callbacks in a single thread', 'A library for real-time events', 'A routing mechanism'], correctAnswer: 'The mechanism that handles asynchronous callbacks in a single thread' }
  ],
  'mongodb mongoose pipelines': [
    { questionText: 'What is MongoDB?', options: ['A relational database', 'A NoSQL document-oriented database', 'A graph database', 'A caching system'], correctAnswer: 'A NoSQL document-oriented database' },
    { questionText: 'What is Mongoose?', options: ['A caching layer for MongoDB', 'An Object Data Modeling (ODM) library for MongoDB and Node.js', 'A frontend framework', 'A SQL to NoSQL converter'], correctAnswer: 'An Object Data Modeling (ODM) library for MongoDB and Node.js' },
    { questionText: 'In a Mongoose schema, what is a SchemaType?', options: ['A database connection', 'The configuration for a specific path (field) like String or Number', 'A validation function', 'A collection index'], correctAnswer: 'The configuration for a specific path (field) like String or Number' },
    { questionText: 'What is the purpose of the aggregation pipeline in MongoDB?', options: ['To connect to multiple databases', 'To process data records and return computed results via a sequence of stages', 'To validate data insertion', 'To create relationships between documents'], correctAnswer: 'To process data records and return computed results via a sequence of stages' },
    { questionText: 'Which aggregation stage is used to filter documents?', options: ['$filter', '$match', '$group', '$project'], correctAnswer: '$match' },
    { questionText: 'What does the $group stage do in an aggregation pipeline?', options: ['Groups documents by a specified identifier and computes accumulated values', 'Sorts documents in ascending order', 'Joins two collections', 'Restricts fields returned in the output'], correctAnswer: 'Groups documents by a specified identifier and computes accumulated values' },
    { questionText: 'Which aggregation stage acts like a SQL JOIN?', options: ['$join', '$lookup', '$merge', '$unwind'], correctAnswer: '$lookup' },
    { questionText: 'What is the purpose of the $unwind stage?', options: ['To reverse a transaction', 'To deconstruct an array field, outputting a document for each element', 'To delete a field', 'To compress the data'], correctAnswer: 'To deconstruct an array field, outputting a document for each element' },
    { questionText: 'How do you specify which fields to include or exclude in the output of a query or aggregation?', options: ['Using $match', 'Using $project', 'Using $select', 'Using $limit'], correctAnswer: 'Using $project' },
    { questionText: 'What is a Mongoose virtual?', options: ['A field that is not stored in MongoDB but is computed on the fly', 'A fake database connection', 'A temporary collection', 'A mocked response for testing'], correctAnswer: 'A field that is not stored in MongoDB but is computed on the fly' },
    { questionText: 'Which method saves a new document to the database in Mongoose?', options: ['Model.add()', 'document.insert()', 'document.save()', 'Model.push()'], correctAnswer: 'document.save()' },
    { questionText: 'What does Model.populate() do?', options: ['Fills the database with dummy data', 'Replaces specified paths in a document with document(s) from other collections', 'Increments a counter', 'Updates all documents in a collection'], correctAnswer: 'Replaces specified paths in a document with document(s) from other collections' },
    { questionText: 'How can you enforce uniqueness on a field in Mongoose?', options: ['unique: true in the schema definition', 'distinct: true in the schema definition', 'Setting a validator function', 'It is not possible in Mongoose'], correctAnswer: 'unique: true in the schema definition' },
    { questionText: 'Which operator is used to increment a numerical field in an update query?', options: ['$add', '$plus', '$inc', '$sum'], correctAnswer: '$inc' },
    { questionText: 'What is the difference between findOneAndUpdate and updateOne?', options: ['updateOne returns the updated document, findOneAndUpdate does not', 'findOneAndUpdate returns the document (original or updated), updateOne only returns the operation status', 'There is no difference', 'updateOne is only for arrays'], correctAnswer: 'findOneAndUpdate returns the document (original or updated), updateOne only returns the operation status' },
    { questionText: 'In an aggregation, what does $sum do inside a $group stage?', options: ['Adds a new field to the document', 'Calculates the sum of collective values from grouped documents', 'Joins two arrays', 'Counts the total number of collections'], correctAnswer: 'Calculates the sum of collective values from grouped documents' },
    { questionText: 'What is an Index in MongoDB?', options: ['The primary key _id', 'A special data structure that stores a small portion of the collection\'s data in an easy-to-traverse form to optimize queries', 'A list of all collections', 'A summary of the database size'], correctAnswer: 'A special data structure that stores a small portion of the collection\'s data in an easy-to-traverse form to optimize queries' },
    { questionText: 'How do you execute an aggregation pipeline using Mongoose?', options: ['Model.aggregate([ stages ])', 'Model.pipeline([ stages ])', 'Model.find().aggregate()', 'Model.group([ stages ])'], correctAnswer: 'Model.aggregate([ stages ])' },
    { questionText: 'What does the $facet stage allow you to do?', options: ['Create a visual dashboard', 'Process multiple aggregation pipelines within a single stage on the same set of input documents', 'Encrypt specific fields', 'Rename fields'], correctAnswer: 'Process multiple aggregation pipelines within a single stage on the same set of input documents' },
    { questionText: 'Why might you use Mongoose middleware (pre/post hooks)?', options: ['To render frontend templates', 'To execute logic like password hashing before saving a document', 'To define routes', 'To connect to the database'], correctAnswer: 'To execute logic like password hashing before saving a document' }
  ],
  'dsa basic algorithms': [
    { questionText: 'What is the time complexity of binary search?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], correctAnswer: 'O(log n)' },
    { questionText: 'Which data structure uses LIFO (Last In First Out)?', options: ['Queue', 'Stack', 'Linked List', 'Tree'], correctAnswer: 'Stack' },
    { questionText: 'Which data structure uses FIFO (First In First Out)?', options: ['Queue', 'Stack', 'Graph', 'Hash Table'], correctAnswer: 'Queue' },
    { questionText: 'What is the worst-case time complexity of QuickSort?', options: ['O(n log n)', 'O(n)', 'O(n^2)', 'O(1)'], correctAnswer: 'O(n^2)' },
    { questionText: 'Which algorithm is best suited for finding the shortest path in an unweighted graph?', options: ['Depth First Search (DFS)', 'Breadth First Search (BFS)', 'Dijkstra\'s Algorithm', 'Kruskal\'s Algorithm'], correctAnswer: 'Breadth First Search (BFS)' },
    { questionText: 'What is a Hash Table?', options: ['A table used for routing network packets', 'A data structure that implements an associative array abstract data type, mapping keys to values', 'A binary tree', 'A sorting algorithm'], correctAnswer: 'A data structure that implements an associative array abstract data type, mapping keys to values' },
    { questionText: 'What is a collision in a Hash Table?', options: ['When the table runs out of memory', 'When two different keys hash to the same index', 'When a key is deleted', 'When the hash function is too slow'], correctAnswer: 'When two different keys hash to the same index' },
    { questionText: 'Which sorting algorithm repeatedly swaps adjacent elements if they are in the wrong order?', options: ['Merge Sort', 'Quick Sort', 'Bubble Sort', 'Insertion Sort'], correctAnswer: 'Bubble Sort' },
    { questionText: 'What is the time complexity of accessing an element in an array by its index?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], correctAnswer: 'O(1)' },
    { questionText: 'What is Dynamic Programming?', options: ['Writing code dynamically at runtime', 'An algorithmic technique for solving an optimization problem by breaking it down into simpler subproblems', 'A frontend state management tool', 'A database querying language'], correctAnswer: 'An algorithmic technique for solving an optimization problem by breaking it down into simpler subproblems' },
    { questionText: 'Which traversal visits the root node, then the left subtree, then the right subtree?', options: ['Inorder', 'Preorder', 'Postorder', 'Level-order'], correctAnswer: 'Preorder' },
    { questionText: 'In a Binary Search Tree (BST), where is the smallest element located?', options: ['At the root', 'The leftmost leaf', 'The rightmost leaf', 'Anywhere'], correctAnswer: 'The leftmost leaf' },
    { questionText: 'What is the primary advantage of a Linked List over an Array?', options: ['Faster access by index', 'Dynamic size and efficient insertions/deletions', 'Less memory usage', 'Better cache locality'], correctAnswer: 'Dynamic size and efficient insertions/deletions' },
    { questionText: 'Which algorithm uses the divide-and-conquer approach?', options: ['Merge Sort', 'Bubble Sort', 'Linear Search', 'Dijkstra\'s Algorithm'], correctAnswer: 'Merge Sort' },
    { questionText: 'What is the space complexity of an iterative DFS using a stack on a graph with V vertices?', options: ['O(1)', 'O(V)', 'O(V^2)', 'O(log V)'], correctAnswer: 'O(V)' },
    { questionText: 'What data structure is typically used to implement a Priority Queue?', options: ['Array', 'Linked List', 'Heap', 'Stack'], correctAnswer: 'Heap' },
    { questionText: 'What is the time complexity of inserting an element into a Max Heap of size n?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctAnswer: 'O(log n)' },
    { questionText: 'Which algorithm finds the Minimum Spanning Tree of a graph?', options: ['Bellman-Ford', 'Kruskal\'s Algorithm', 'Floyd-Warshall', 'A* Search'], correctAnswer: 'Kruskal\'s Algorithm' },
    { questionText: 'What is memoization?', options: ['Memorizing syntax', 'Caching the results of expensive function calls to avoid repeating them', 'Writing comments in code', 'Allocating memory in C++'], correctAnswer: 'Caching the results of expensive function calls to avoid repeating them' },
    { questionText: 'What is the time complexity of finding a cycle in a Linked List using Floyd\'s Tortoise and Hare algorithm?', options: ['O(1)', 'O(n)', 'O(n^2)', 'O(log n)'], correctAnswer: 'O(n)' }
  ],
  'system design basics': [
    { questionText: 'What is Load Balancing?', options: ['Balancing the budget of a cloud architecture', 'Distributing incoming network traffic across multiple servers to ensure reliability', 'Compressing data to save bandwidth', 'Allocating memory equally to all processes'], correctAnswer: 'Distributing incoming network traffic across multiple servers to ensure reliability' },
    { questionText: 'What is Horizontal Scaling?', options: ['Adding more CPU and RAM to an existing server', 'Adding more servers to a pool of resources', 'Scaling the UI for ultra-wide monitors', 'Splitting a database table into columns'], correctAnswer: 'Adding more servers to a pool of resources' },
    { questionText: 'What does CDN stand for and what is its purpose?', options: ['Central Data Node; stores the primary database', 'Content Delivery Network; caches static assets physically closer to users to reduce latency', 'Code Deployment Network; CI/CD pipeline', 'Cascading Data Node; handles database replication'], correctAnswer: 'Content Delivery Network; caches static assets physically closer to users to reduce latency' },
    { questionText: 'What is the CAP Theorem?', options: ['A limit on database storage', 'A principle stating a distributed system can only provide 2 out of 3: Consistency, Availability, Partition Tolerance', 'A rule for API rate limiting', 'A theorem for calculating bandwidth'], correctAnswer: 'A principle stating a distributed system can only provide 2 out of 3: Consistency, Availability, Partition Tolerance' },
    { questionText: 'What is Database Sharding?', options: ['Encrypting the database', 'Splitting a large database horizontally across multiple servers to improve performance', 'Backing up the database daily', 'Adding indexes to a table'], correctAnswer: 'Splitting a large database horizontally across multiple servers to improve performance' },
    { questionText: 'Which cache eviction policy removes the item that has not been used for the longest time?', options: ['FIFO (First In First Out)', 'LIFO (Last In First Out)', 'LRU (Least Recently Used)', 'LFU (Least Frequently Used)'], correctAnswer: 'LRU (Least Recently Used)' },
    { questionText: 'What is the purpose of a Reverse Proxy?', options: ['To hide the client\'s IP address', 'To sit in front of web servers and forward client requests to them', 'To reverse the order of database queries', 'To prevent DDOS attacks exclusively'], correctAnswer: 'To sit in front of web servers and forward client requests to them' },
    { questionText: 'What is a Message Broker (e.g., RabbitMQ, Kafka)?', options: ['A tool for sending marketing emails', 'An intermediary program that translates messages from the formal messaging protocol of the sender to the receiver, enabling asynchronous communication', 'A load balancer for databases', 'A real-time chat application'], correctAnswer: 'An intermediary program that translates messages from the formal messaging protocol of the sender to the receiver, enabling asynchronous communication' },
    { questionText: 'What is Microservices Architecture?', options: ['An application built as a single, indivisible unit', 'Structuring an application as a collection of loosely coupled, independently deployable services', 'Using micro-computers for hosting', 'A frontend design pattern'], correctAnswer: 'Structuring an application as a collection of loosely coupled, independently deployable services' },
    { questionText: 'What is Event Sourcing?', options: ['Finding sources for news events', 'Storing the state of a system as a sequence of state-changing events', 'Triggering UI events in JavaScript', 'A logging framework'], correctAnswer: 'Storing the state of a system as a sequence of state-changing events' },
    { questionText: 'What is the primary benefit of read replicas in a database?', options: ['They allow faster write operations', 'They provide automatic backups', 'They scale out read operations by distributing the load', 'They automatically shard the data'], correctAnswer: 'They scale out read operations by distributing the load' },
    { questionText: 'What does "Eventual Consistency" mean?', options: ['The system is never consistent', 'Updates are guaranteed to propagate to all nodes eventually, but not immediately', 'Data is consistent only when an event occurs', 'The database will eventually crash'], correctAnswer: 'Updates are guaranteed to propagate to all nodes eventually, but not immediately' },
    { questionText: 'What is API Rate Limiting?', options: ['Limiting the speed of the internet connection', 'Controlling the number of requests a client can make to an API within a specified time frame', 'Limiting the number of APIs an application can use', 'Restricting API access to premium users only'], correctAnswer: 'Controlling the number of requests a client can make to an API within a specified time frame' },
    { questionText: 'What is an API Gateway?', options: ['A router in a home network', 'A server that acts as an API front-end, receiving requests, enforcing security, and routing them to backend services', 'A payment processing portal', 'A DNS provider'], correctAnswer: 'A server that acts as an API front-end, receiving requests, enforcing security, and routing them to backend services' },
    { questionText: 'What is the main difference between SQL and NoSQL databases?', options: ['SQL databases are schema-less, NoSQL has strict schemas', 'SQL databases are relational and structured, NoSQL databases are non-relational and highly scalable for unstructured data', 'NoSQL is always faster than SQL', 'SQL is only for cloud environments'], correctAnswer: 'SQL databases are relational and structured, NoSQL databases are non-relational and highly scalable for unstructured data' },
    { questionText: 'What is Long Polling?', options: ['A survey technique', 'A technique where the client requests information and the server holds the connection open until new data is available', 'A WebSockets alternative that is faster', 'Polling a database every millisecond'], correctAnswer: 'A technique where the client requests information and the server holds the connection open until new data is available' },
    { questionText: 'What is a Single Point of Failure (SPOF)?', options: ['A bug in a specific function', 'A part of a system that, if it fails, will stop the entire system from working', 'A failure caused by a single user', 'A node in a distributed system'], correctAnswer: 'A part of a system that, if it fails, will stop the entire system from working' },
    { questionText: 'Which algorithm is commonly used for consistent hashing?', options: ['MD5', 'SHA-256', 'A virtual ring (hash ring) mapping nodes and keys', 'RSA'], correctAnswer: 'A virtual ring (hash ring) mapping nodes and keys' },
    { questionText: 'What is Data Normalization?', options: ['Converting data to a standard format (e.g. JSON)', 'Organizing database tables to reduce redundancy and improve data integrity', 'Making all servers run the same OS', 'Restoring a database from a backup'], correctAnswer: 'Organizing database tables to reduce redundancy and improve data integrity' },
    { questionText: 'What is a Bloom Filter?', options: ['A camera filter for UI', 'A space-efficient probabilistic data structure used to test whether an element is a member of a set', 'A query optimizer in SQL', 'A method to filter spam emails'], correctAnswer: 'A space-efficient probabilistic data structure used to test whether an element is a member of a set' }
  ]
};

const getQuizBankQuestions = (topic, numQuestions, marksPerQuestion) => {
  const t = topic.toLowerCase();
  
  // Find the exact or closest matching topic
  let selectedTopic = 'react.js advanced'; // default fallback
  for (const key of Object.keys(quizBank)) {
    if (t.includes(key) || key.includes(t)) {
      selectedTopic = key;
      break;
    }
  }

  const genericQuestions = [...quizBank[selectedTopic]];
  const shuffled = genericQuestions.sort(() => 0.5 - Math.random());
  
  const fallbackQuestions = Array.from({ length: numQuestions }).map((_, idx) => {
    // Loop through available questions if numQuestions > available questions (usually we have 20)
    const template = shuffled[idx % shuffled.length];
    return {
      questionText: template.questionText,
      options: template.options,
      correctAnswer: template.correctAnswer,
      marks: marksPerQuestion
    };
  });

  return fallbackQuestions;
};

module.exports = getQuizBankQuestions;
